import {
  Archive,
  ArrowUp,
  AtSign,
  Bell,
  BookOpen,
  Bot,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  Info as CircleInfo,
  Command,
  File,
  FileCode2,
  FileText,
  Filter,
  Folder,
  GitBranch,
  Globe2,
  Grid2X2,
  Home,
  Infinity as InfinityIcon,
  Languages,
  LayoutList,
  Menu,
  MessageSquare,
  Mic,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Play,
  Plus,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Shrink,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Square,
  Star,
  Target,
  Terminal,
  Trash2,
  User,
  WandSparkles,
  X,
  Zap,
  type LucideIcon
} from "lucide-react";
import type { SVGProps } from "react";

export type IconName =
  | "add" | "archive" | "arrow-up" | "at" | "bell" | "book" | "bot" | "check" | "chevron" | "chevron-down"
  | "close" | "command" | "compress" | "file" | "file-code" | "filter" | "folder" | "git" | "globe"
  | "grid" | "help" | "home" | "infinity" | "info" | "languages" | "list" | "menu" | "message" | "mic"
  | "more" | "panel" | "panel-left" | "panel-left-close" | "panel-right" | "panel-right-close"
  | "play" | "refresh" | "search" | "send" | "server" | "settings" | "shield" | "shopping" | "sparkles"
  | "star" | "stop" | "target" | "terminal" | "trash" | "user" | "wand" | "warning" | "zap";

const icons: Record<IconName, LucideIcon> = {
  add: Plus,
  archive: Archive,
  "arrow-up": ArrowUp,
  at: AtSign,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  check: Check,
  chevron: ChevronRight,
  "chevron-down": ChevronDown,
  close: X,
  command: Command,
  compress: Shrink,
  file: File,
  "file-code": FileCode2,
  filter: Filter,
  folder: Folder,
  git: GitBranch,
  globe: Globe2,
  grid: Grid2X2,
  help: CircleHelp,
  home: Home,
  infinity: InfinityIcon,
  info: CircleInfo,
  languages: Languages,
  list: LayoutList,
  menu: Menu,
  message: MessageSquare,
  mic: Mic,
  more: MoreHorizontal,
  panel: PanelRightOpen,
  "panel-left": PanelLeftOpen,
  "panel-left-close": PanelLeftClose,
  "panel-right": PanelRightOpen,
  "panel-right-close": PanelRightClose,
  play: Play,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: ShieldCheck,
  shopping: ShoppingBag,
  sparkles: Sparkles,
  star: Star,
  stop: Square,
  target: Target,
  terminal: Terminal,
  trash: Trash2,
  user: User,
  wand: WandSparkles,
  warning: CircleAlert,
  zap: Zap
};

export function Icon({ name, ...props }: { name: IconName } & SVGProps<SVGSVGElement>) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={1.75} {...props} />;
}
