import Link from "next/link";
import React from "react";
import { RequirementGateBadge, RequirementStatusBadge } from "@/components/requirements/requirement-status";
import { WindowSection } from "@/components/ui/window-section";
import { buildNeoSurfaceClassName } from "@/lib/theme";
import type { RequirementPackageDetail, RequirementSpecDetail } from "@/lib/types";

export function RequirementPackagePage({ requirement }: { requirement: RequirementPackageDetail }) {
  return <div className="space-y-5 md:space-y-6">
    <Link href="/requirements" className="text-sm text-slate-500 underline underline-offset-4 hover:text-ink">← All requirements</Link>
    <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_300px]">
      <div className={`${buildNeoSurfaceClassName("panel", "blue")} space-y-3 p-4`}>
        <p className="font-mono text-[11px] uppercase tracking-[0.14em] text-slate-500">{requirement.id}</p>
        <div className="flex flex-wrap items-start justify-between gap-3"><h1 className="text-2xl font-semibold text-ink">{requirement.title}</h1><RequirementStatusBadge status={requirement.status} /></div>
        <p className="text-sm leading-6 text-slate-600">GoalSpec Requirement Package · {requirement.specCount} child specs</p>
        {requirement.warnings.length ? <p className="border-l-2 border-red-500 pl-3 text-sm leading-6 text-red-800">{requirement.warnings.join(" / ")}</p> : null}
      </div>
      <div className={`${buildNeoSurfaceClassName("panel", "mint")} p-4`}><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-slate-500">package gate</p><div className="mt-2 flex items-center justify-between"><span className="text-sm">index + PRD + child specs</span><RequirementGateBadge status={requirement.gates.package} /></div></div>
    </div>
    <WindowSection title="Package overview" description="The package-level contract and acceptance criteria." variant="plain" tint="neutral">
      <div className="grid gap-3 sm:grid-cols-2"><SourceLink href={`/requirements/${requirement.id}/prd`} label="PRD" path={`${requirement.id}/prd.md`} present={requirement.files.prd.present} /><SourceLink href={`/requirements/${requirement.id}/acceptance`} label="Acceptance" path={`${requirement.id}/acceptance.md`} present={requirement.files.acceptance.present} /></div>
    </WindowSection>
    <WindowSection title="Child specs" description="Each SNN-slug is an independently reviewable implementation contract." variant="plain" tint="violet">
      {requirement.specs.length ? <div className="grid gap-3 md:grid-cols-2">{requirement.specs.map((spec) => <Link key={spec.id} href={`/requirements/${requirement.id}/specs/${spec.id}`} className={`${buildNeoSurfaceClassName("row")} block p-4 transition hover:border-slate-400/50`}><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-slate-500">{spec.id}</p><h3 className="mt-1 font-semibold text-ink">{spec.title}</h3></div><span className="text-xs text-slate-500">{spec.status}</span></div><p className="mt-3 text-xs text-slate-500">spec.md · test.md · review.md · issues/</p></Link>)}</div> : <p className="text-sm text-amber-900">No child specs are readable yet.</p>}
    </WindowSection>
  </div>;
}
function SourceLink({ href, label, path, present }: { href: string; label: string; path: string; present: boolean }) { return <Link href={href} className="rounded-md border border-line/70 bg-canvas p-3"><span className="block text-sm font-medium text-ink">{label}</span><span className={`mt-1 block font-mono text-xs ${present ? "text-slate-500" : "text-red-700"}`}>{path} · {present ? "ready" : "missing"}</span></Link>; }
export function RequirementSpecPage({ spec }: { spec: RequirementSpecDetail }) { return <div className="space-y-5 md:space-y-6"><Link href={`/requirements/${spec.requirementId}`} className="text-sm text-slate-500 underline underline-offset-4 hover:text-ink">← Package overview</Link><div className={`${buildNeoSurfaceClassName("panel", "blue")} space-y-2 p-4`}><p className="font-mono text-[11px] uppercase tracking-[0.14em] text-slate-500">{spec.id}</p><div className="flex flex-wrap items-start justify-between gap-3"><h1 className="text-2xl font-semibold text-ink">{spec.title}</h1><span className="text-sm text-slate-500">{spec.status}</span></div><p className="text-sm text-slate-600">{spec.path}</p></div><nav className="flex flex-wrap gap-2" aria-label="Spec documents">{(["spec", "test", "review", "issues"] as const).map((doc) => <a key={doc} href={`#${doc}`} className="rounded-md border border-line/60 px-3 py-2 text-sm text-slate-500 hover:text-ink">{doc}.md</a>)}</nav>{(["spec", "test", "review", "issues"] as const).map((doc) => <WindowSection key={doc} title={doc === "spec" ? "Spec" : doc} description={spec.sources[doc]?.path ?? `${doc}.md is missing`} variant="plain" tint={spec.sources[doc] ? "neutral" : "amber"}><div id={doc}>{spec.sources[doc] ? <pre className="max-h-[560px] overflow-auto whitespace-pre-wrap rounded-md border border-line/70 bg-canvas p-4 font-mono text-xs leading-6 text-slate-700">{spec.sources[doc]?.source}</pre> : <p className="text-sm text-amber-900">This artifact is missing.</p>}</div></WindowSection>)}<WindowSection title="Evidence" description="Evidence is scoped to this child spec." variant="plain" tint="mint">{spec.evidence.length ? <ul className="list-disc pl-5 text-sm text-slate-600">{spec.evidence.map((entry) => <li key={entry}>{entry}</li>)}</ul> : <p className="text-sm text-slate-600">No evidence artifacts recorded yet.</p>}</WindowSection></div>; }
export function RequirementNotFound({ requirementId }: { requirementId: string }) { return <WindowSection title="Requirement package unavailable" description={`No readable Requirement Package was found for ${requirementId}.`} variant="plain" tint="amber"><p className="border-l-2 border-amber-500 pl-3 text-sm leading-6 text-amber-900">Check `.requirements/requirements/{requirementId}/index.yaml` and `specs/SNN-*/`.</p></WindowSection>; }
export function RequirementSpecNotFound({ requirementId, specId }: { requirementId: string; specId: string }) { return <WindowSection title="Child spec unavailable" description={`No readable ${specId} was found in ${requirementId}.`} variant="plain" tint="amber"><p className="text-sm text-amber-900">The route reads child specs from the selected Requirement Package.</p></WindowSection>; }
